project:
  type: website
  output-dir: docs

website:
  title: "Navigate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - learn.qmd
      - test.qmd
      - explore.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



